[build]
  publish = "public"
  functions = "netlify/functions" # Πρέπει να είναι ο φάκελος που περιέχει το function σου (το "server" function)

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions" # Αυτό είναι το ίδιο με το functions, απλά επιβεβαιώνεται
